language: python

sudo: true

python:
  - "3.8"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.npm
    - $HOME/.nvm
    - $HOME/.cache/node_modules
    - $HOME/.cache/venvs

env:
  - DJANGO_SETTINGS_MODULE=backend.test_settings

install:
  - pipenv install --dev
  - pip install --upgrade requests
  - cd frontend
  - npm install
  - cd ..

script:
  - python backend/manage.py makemigrations --settings=backend.test_settings
  - python backend/manage.py migrate --settings=backend.test_settings
  - cd backend
  - pytest
  - cd ../frontend
  - npm test

after_success:
- coveralls
