# Generated by Django 3.1.1 on 2020-09-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200928_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_header',
            field=models.ImageField(blank=True, upload_to='posts/photos'),
        ),
    ]
